// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package attachment

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	KeepassFile     *string `mapstructure:"keepass_file" required:"true" cty:"keepass_file" hcl:"keepass_file"`
	KeepassPassword *string `mapstructure:"keepass_password" required:"true" cty:"keepass_password" hcl:"keepass_password"`
	AttachmentPath  *string `mapstructure:"attachment_path" required:"true" cty:"attachment_path" hcl:"attachment_path"`
	Destination     *string `mapstructure:"destination" required:"true" cty:"destination" hcl:"destination"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"keepass_file":     &hcldec.AttrSpec{Name: "keepass_file", Type: cty.String, Required: false},
		"keepass_password": &hcldec.AttrSpec{Name: "keepass_password", Type: cty.String, Required: false},
		"attachment_path":  &hcldec.AttrSpec{Name: "attachment_path", Type: cty.String, Required: false},
		"destination":      &hcldec.AttrSpec{Name: "destination", Type: cty.String, Required: false},
	}
	return s
}
